### ISSUE TITLE
Having problems getting the example to run

### ISSUE THREAD

**Issue by awdriggs** [fivdi/spi-device#1]
Hey Brian,
I can't get the example code to run on my raspi. 

First, I'm getting this error...

```
/home/pi/Documents/raspi-test/spi-test.js:14
if (err) throw err;
               ^
Error: ENOENT, No such file or directory
    at Error (native)
```

I have tried commenting out that line, and then I get this error..
```
home/pi/Documents/raspi-test/spi-test.js:16
  mcp3008.transfer(message, function(err, message) {
          ^
Error: EPERM, device closed, operation not permitted
    at Error (native)
    at /home/pi/Documents/raspi-test/spi-test.js:16:11
```

I'm totally new to hacking with a pi, and this is the first test that I've tried. So any advice you have to resolve would be helpful. Could it be a problem with my breadboarding?

**Comment by awdriggs** [comment]
by the way, i'm running 'v0.12.6' of node, which I installed using the apt.adafruit.com package repository, following a tutorial for your other package onoff

**Comment by fivdi** [comment]
It looks like SPI isn't enabled on the Pi. To enable SPI use the `raspi-config` tool:
```
sudo raspi-config
```
Navigate to `"Advanced Options >> SPI"` and answer the question `"Would you like the SPI interface to be enabled?"` with `Yes`.

Depending on the version of Raspbian being used, the Pi may need a reboot for the change to take effect.

**Comment by awdriggs** [comment]
Awesome. Doing that worked.

I was still getting an error on `if (err) throw err;` but I commented out that line and was fine. Any idea why that line would be a problem?

**Comment by fivdi** [comment]
There shouldn't be any error. Please post the complete code for the program that's throwing the error.

**Comment by awdriggs** [comment]
Nevermind. It was my error. Thanks again for you help.
