### ISSUE TITLE
Help with spi-device and THAT5171 chip

### ISSUE THREAD

**Issue by PhelarNord** [fivdi/spi-device#10]
Hi!

I´ve made a proto board containing a THAT5171 chip. 
http://www.thatcorp.com/datashts/THAT_5171_Datasheet.pdf -spi info on page 12.

I have issues to communicate with the chip using a raspberry pi as master.
I´m pretty sure that all the hardware is wired correctly.
I´ve tried to "modify" the example code but....
My nearest goal is to get som responce from the chip via the register adress, 3bits, CHIP_ ID

Very grateful for some help

```js
const spi = require('spi-device');
 

const pre = spi.open(0, 0, err => { // Is this right for my device?
  // An SPI message is an array of one or more read+write transfers
  const message = [{
    sendBuffer: Buffer.from([0,0,]), //Does binary work here or hex?
    receiveBuffer: Buffer.alloc(1),              
    byteLength: 1, //Prepare master for receiving byteLength? THAT5171 should return 8 bits.
    speedHz: 10000000 // Does this work? 10Mhz or do i get like 7,8
  }];
 
  if (err) throw err;
 
  pre.transfer(message, (err, message) => {
    if (err) throw err;
 
    const data = message[0].receiveBuffer[1];      
   
 
    console.log(data);
  });
});
```

**Comment by fivdi** [comment]
In the description of the SPI signals on page 12 of the datasheet the following is stated:

`The SPI protocol consists of 16-bit read and write commands `

However, the code posted above assumes that message are 8-bits long, not a 16-bits long, as `byteLength` is 1. If I'm not mistaken the message should be created as follows:
```js
  const message = [{
    sendBuffer: Buffer.from([0,0]), // Modified. Removed unnecessary comma.
    receiveBuffer: Buffer.alloc(2), // Modified. Replaced 1 with 2.
    byteLength: 2, // Modified. Replaced 1 with 2.
    speedHz: 10000000
  }];
```
When the read has completed, the byte read should be in `receiveBuffer[1]`

Answers to the additional questions in the source code can be found below.

```js
const pre = spi.open(0, 0, err => { // Is this right for my device? If I understand the datasheet correctly and the device is connected up as device 0 on bus 0 then this is correct.
  const message = [{
    sendBuffer: Buffer.from([0,0,]), //Does binary work here or hex? Binary, decimal and hex work. For example, 0b00011000, 24 and 0x18 all mean the same thing here.
    receiveBuffer: Buffer.alloc(1),              
    byteLength: 1, //Prepare master for receiving byteLength? No, byteLength is the message length which is 2 not 1.
    speedHz: 10000000 // Does this work? 10Mhz or do i get like 7,8. 10000000 can be specified as the device can be clocked at speeds of up to 10MHz according to the datasheet. To verify that it really is 10MHz a scope would be needed.
  }];
```

**Comment by fivdi** [comment]
If the device should always be clocked at 10MHz this can be specified once with the `maxSpeedHz` option when `open` is invoked rather than specifying it in every message with the `speedHz` option when `transfer` is invoked.

**Comment by PhelarNord** [comment]
Thanks a lot!
I have done the changes and run the code but a just get a singel 0 from the "data" variable :/


"const pre = spi.open(0, 0, err =>"

I´m not shure about this , the bus and the device. What is the bus setting, the chip is connected directly to the pi, no multipel slaves. 
I´ve set the chip adress with pull down resistors, all the chip gpio´s to ground. Is it the chip adress you refer to as device in spi.open?

**Comment by fivdi** [comment]
> I´m not shure about this , the bus and the device. What is the bus setting, the chip is connected directly to the pi, no multipel slaves.

If the following is true, then bus 0 and device 0 is correct:
- MOSI on Pi connected to DIN on THAT5171
- MISO on Pi connected to DOUT on THAT5171
- SCLK on Pi connected to SCLK on THAT5171
- CS0 on Pi connected to CS on THAT5171

> I´ve set the chip adress with pull down resistors, all the chip gpio´s to ground. Is it the chip adress you refer to as device in spi.open?

The chip address is not related to the SPI device number. The chip address is something that is specific to the THAT5171. If the chip address is set to 0 with pull-down resistors, then the A0, A1, and A2 bits in messages must be set to 0 to communicate with the device.

Note that there is a lot of other information in the datasheet that is also relevant. For example, the THAT5171 has a RST pin for resetting the device. Is this pin being used correctly in the circuit?

**Comment by PhelarNord** [comment]
Nope, i think i´ve implemented the RST the wrong way:/

Thanks for all the help!! Really grateful:)
I´ll close this issue now when this matter deviates from the main subject.

**Comment by fivdi** [comment]
If the RST pin is the only remaining issue then it could be connected to a free GPIO on the Raspberry Pi and controlled with [onoff](https://github.com/fivdi/onoff).

**Comment by PhelarNord** [comment]
Solved this today:) A cap and a resistor at the rst pin. The chip is now responding, thanks!

**Comment by blakethepatton** [comment]
Different chip and different situation, but going through this ticket helped me figure out that I had my clock speed off by 10x. If anyone else is struggling converting mhz to hz, just multiply by 10^6 or, supposing you need 4mhz, provide 4e6 as the value for speed.
