### ISSUE TITLE
SPI - question to control a push button with bitmap in SPI

### ISSUE THREAD

**Issue by yboujraf** [fivdi/spi-device#12]
Dear @fivdi 

I 'd like to use your library to control this push button from NKK Smartswitch in SPI.

I am not asking to do it but I 'd like just to understand with the information I have found in your sample code to monitor temperature with mcp3008

This is the datasheet

![image](https://user-images.githubusercontent.com/6151258/71522067-7848eb80-28c3-11ea-8bfb-57f9ce48b5b5.png)

I underlined the most important informat and would be sure I am right and could use your lib with success.

### switch : GPIO
```
SW - Terminal of Switch Normally open
SW  - Terminal of Switch Normally open
```

=> I should use https://github.com/fivdi/onoff for the button with debounce. Is it right ?

### LCD : SPI
```
SDO  - Data Out Data output line for SPI
SDI - Data In Data input line for SPI
SCK - Serial Clock Clock line for SPI that synchronizes commands and data

SS - Slave Select Chip select for SPI; line is active low
```

I see the cabling

![image](https://user-images.githubusercontent.com/6151258/71522384-cc080480-28c4-11ea-88a2-4a980502df9a.png)

=> I should use https://github.com/fivdi/mcp-spi-adc for the SPI with CS or https://github.com/fivdi/spi-device . Is it right?

To be sure Ia m understanding : for the pin layout regarding my raspberry PI4 :

![image](https://user-images.githubusercontent.com/6151258/71523019-69643800-28c7-11ea-8938-9da5d873acc5.png)

SPI0 MISO <=> SDO from my button
SPI0 MOSI <=>SDI from my button
SPI SCLK <-> SCK
SPI CE0 <-> SS but each time I need to send a message I need to force "false" till the message is sent then when terminate I need to force a true the SS. I don't know if SPI CE0 is enabled when false or true?

Thanks for your remarks.

Best Regards,
Youssef

**Comment by fivdi** [comment]
I'm not familiar with the NKK Smartswitch so the information provided in the answer here isn't coming from an NKK Smartswitch expert.

It looks like this is a 5V device but the Raspberry Pi is a 3.3V device. This means the appropriate logic level converters would be needed. Alternatively, perhaps there are 3.3V NKK Smartswitchs available.

An SPI clock frequency of 8MHz should not be a problem for the Raspberry Pi or the spi-device Node.js module.

>switch : GPIO
>
>SW - Terminal of Switch Normally open
>SW  - Terminal of Switch Normally open
>
>=> I should use https://github.com/fivdi/onoff for the button with debounce. Is it right ?

Yes, this should work.

> LCD : SPI
> ...
> => I should use https://github.com/fivdi/mcp-spi-adc for the SPI with CS or https://github.com/fivdi/spi-device . Is it right?

https://github.com/fivdi/spi-device can be used. https://github.com/fivdi/mcp-spi-adc can't be used as it's only for MCP3xxx analog to digital converters.

>SPI0 MISO <=> SDO from my button
>SPI0 MOSI <=>SDI from my button
>SPI SCLK <-> SCK

Yes, this is correct.

>SPI CE0 <-> SS but each time I need to send a message I need to force "false" till the message is sent then when terminate I need to force a true the SS. I don't know if SPI CE0 is enabled when false or true?

SPI CE0 should be connected to SS, however, you will not need to control the SS line yourself, this will be handled by spi-device automatically.

**Comment by yboujraf** [comment]
Dear @fivdi 

Thanks a lot for your confirmation 🥇 

The Raspberry PI4 has 3.3V and 5V distributed but could use external power because my second oled button needs 16v for the backlight 65k color display.


### SpiOptions -  lsbFirst

I have seen in the https://github.com/fivdi/spi-device/blob/master/spi-device.d.ts there is a properties to :

```
export type SpiOptions = {
    mode?: SpiMode, // 2-bit, MODE0, MODE1, MODE2, or MODE3, default MODE0
    chipSelectHigh?: boolean, // true for active high chip select, default false
    lsbFirst?: boolean, // true for least significant bit first transfer, default false
    threeWire?: boolean, // true for shared MISO/MOSI signals, default false
    loopback?: boolean, // true for loopback mode, default false
    noChipSelect?: boolean, // true for 1 device per bus, no chip select, default false
    ready?: boolean, // true if device pulls low to pause, default false
    bitsPerWord?: number, // 8-bit, device word size, default 8
    maxSpeedHz?: number // 32-bit, device clock frequency in Hertz, default system specific
}
```

```
 lsbFirst?: boolean, // true for least significant bit first transfer, default false
```

When generating a bitmap, I need to send data with LSB first but not for the command.

![image](https://user-images.githubusercontent.com/6151258/71539986-a28ebd80-2944-11ea-855b-7d314142756d.png)

That means each byte I need use **>>8** to get msb -> LSB.

Like this :

```
( D0 D1 D2 D3 D4 D5 D6 D7 >> 8 ) result (D7 D6 D5 D4 D3 D2 D1 D0)
```

 Is it right ? 

Best Regards
Youssef

**Comment by fivdi** [comment]
> The Raspberry PI4 has 3.3V and 5V distributed but could use external power because my second oled button needs 16v for the backlight 65k color display.

Yes, the Raspberry Pi supplies 3.3V and 5V on the GPIO header. However, all GPIO pins including the SPI pins are not 5V tolerant, they are 3.3V tolerant.

> That means each byte I need use >>8 to get msb -> LSB.

Yes, it looks like you will need to reverse the bits in each byte of the bitmap. Note that in JavaScript `>>` is the right-shift operator, not a reverse bits operator.

**Comment by fivdi** [comment]
On seconds thoughts, looking at the bottom half of the image in [this post](https://github.com/fivdi/spi-device/issues/12#issuecomment-569392223) where is says "Transferring Display Data/Displaying LCD Command and Data Sequence" it looks like it isn't actually necessary to reverse the bits in each byte of the bitmap,

**Comment by yboujraf** [comment]
Dear @fivdi 

Regarding your comment 

Yes, it looks like you will need to reverse the bits in each byte of the bitmap. Note that in JavaScript >> is the right-shift operator, not a reverse bits operator.

Not understood **in JavaScript >> is the right-shift operator, not a reverse bits operator.**

Best Regards
Youssef

**Comment by fivdi** [comment]
> Not understood in JavaScript >> is the right-shift operator, not a reverse bits operator.

For a description of the right-shift operator see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_Operators#Right_shift

What's needed is a revers bits in byte, not a shift bits right. See https://stackoverflow.com/questions/2602823/in-c-c-whats-the-simplest-way-to-reverse-the-order-of-bits-in-a-byte/2603254

**Comment by yboujraf** [comment]
Dear @fivdi 

It was my first exercice in ASM. My teacher when he designed his board he reverted all the 8 bits but to control his eprom.

Then My first option was to make a Look up table but he said I don't enough memeory.
I need to find few line of ASM code to invert the value and I did it but 25 years ago.
Now with new language, the way to write a code are too different and in asm I was able to control the timing of my software, function, .... here I don't know.

I will try your link and let you know the end. 

But sure today I will control the button.

Just missing an extra library able to me to draw line, rectangle, square, text, ... because here in the command, there is only bitmap :-(

Again thanks for your time.

If you are living in Belgium, with plaisure to share a beer and chocolate with you.

Best Regards
Youssef

**Comment by fivdi** [comment]
>If you are living in Belgium, with plaisure to share a beer and chocolate with you.

I'll be sure to let you know if I'm in Belgium :smiley: 

Good luck with the smartswitch.

**Comment by yboujraf** [comment]
Are you working in the broadcast industry ?

BR

**Comment by fivdi** [comment]
No, the electronics industry.

**Comment by yboujraf** [comment]
Dear @fivdi 

I hope you are well.

I tried the GPIO library and with the button it works. just need to adapt the bounce.

I enable the SPI through raspi-config

regarding SPI, I tried but don't know if I could have a monitoring of what i am sending or to scan SPI port and see if any device is connected like i2cDetect.

I tried this sample code but nothing happen.

I don't know if this is the option are wrong following the datasheet.

CEO needs to be at false when sendind data and back the true at the end.
Otherwise, when opening the SPI, open(busNumber, deviceNumber[, options], cb)
But i don't have the device number and nothing in the datasheet.
I let to "0";

If you have any idea if my settings are correct or wrong. It will be great.
```

'use strict';

const spi = require('bindings')('spi');

// Determine the temperature using a TMP36 analog temperature sensor wired to
// channel 5 on an MCP3008 SPI A/D converter

const options = {
  mode: spi.MODE0,
  chipSelectHigh: false,
  lsbFirst: false, // pi only supports msb first
  threeWire: false,
  loopback: false, // pi doesn't support loopback
  noChipSelect: true,
  ready: false, // pi doesn't support ready
  bitsPerWord: 8, // pi only supports 8 bit words
  maxSpeedHz: 8000000 //Hz
};
const nkk_switch = spi.open(0, 0, options, err => {
  // An SPI message is an array of one or more read+write transfers

  const message = [{
    sendBuffer: Buffer.from([ 0x40, 0x03, 0x41, 0x1F]), // Sent to rinitialize
    //receiveBuffer: Buffer.alloc(3),              // Raw data rno answer
    byteLength: 4,
    chipSelectChange : false,
    speedHz: 8000000 // Use a low bus speed to get a good reading from the TMP36
  }];

  if (err) {
    throw err;
  }

  nkk_switch.transfer(message, (err, message) => {
    if (err) {
      throw err;
    }

   
    console.log('sent initialize');

  });

  const message1 = [{
    sendBuffer: Buffer.from([0x40, 0x33, 0x41, 0xBF]), // Sent backlight RED FULL
    //receiveBuffer: Buffer.alloc(3),              // Raw data read 
    byteLength: 4,
    chipSelectChange : false,
    speedHz: 8000000 
  }];
  nkk_switch.transfer(message1, (err, message) => {
    if (err) {
      throw err;
    } 
    console.log('sent message1');
  });
});

```

I have no error but not feedback or nothing on the button :-(

Best Regards,
Youssef

**Comment by fivdi** [comment]
>I tried the GPIO library and with the button it works. just need to adapt the bounce.

That's good news.

>regarding SPI, I tried but don't know if I could have a monitoring of what i am sending or to scan SPI port and see if any device is connected like i2cDetect.

I'm not aware of a scanner for SPI similar to i2cdetect for I2C.

>CEO needs to be at false when sendind data and back the true at the end.

In this case, CE0 on the Raspberry Pi should be connected to SS on the SmartSwitch and the option `noChipSelect` should either be set to `false` or omitted. In the code above, `noChipSelect` is set to `true`
```js
  noChipSelect: true,
```
it should be
```js
  noChipSelect: false,
```

>Otherwise, when opening the SPI, open(busNumber, deviceNumber[, options], cb)
>But i don't have the device number and nothing in the datasheet.
>I let to "0";

If the SmartSwitch is connected to the Pi as shown in the images from the first post above then the `busNumber` is 0 and the `deviceNumber` is 0. The `busNumber` is 0 because the pins for SPI0 are being used. The `deviceNumber` is 0 because pin SPI CE0 is used to select the device.

>    chipSelectChange : false,

The default value for `chipSelectChange` is false so setting it it false will have no effect, This can be omitted. Also, the messages being sent only contains one transfer so this option will have no effect.

>   mode: spi.MODE0,

Have you checked the datasheet to ensure that `MODE0` is the correct mode for the device?

**Comment by yboujraf** [comment]
Dear @fivdi 

Again thanks.

I will do it.

Regarding the SPI MODE 0. Nothing in the pdf file but I have seen SPI Timing chart (/SS Using)

![image](https://user-images.githubusercontent.com/6151258/71554302-c114b780-2a1d-11ea-9a6b-9f10b3a8d337.png)

The pdf in case I forgot to share you the good information.

[smart_switch_lcd6432_IS.pdf](https://github.com/fivdi/spi-device/files/4007899/smart_switch_lcd6432_IS.pdf)

Best Regards
Youssef

**Comment by yboujraf** [comment]
Dear @fivdi 

It's works
I checked the SPI Timing chart and discovered it is MODE2.

Here I have just sent the procedure to initialyze and the send backlight to GREEN.

'use strict';

const spi = require('bindings')('spi');

// Determine the temperature using a TMP36 analog temperature sensor wired to
// channel 5 on an MCP3008 SPI A/D converter

const options = {
  mode: spi.MODE2,
  chipSelectHigh: false,
  lsbFirst: false, // pi only supports msb first
  threeWire: false,
  loopback: false, // pi doesn't support loopback
  noChipSelect: false,
  ready: false, // pi doesn't support ready
  bitsPerWord: 8, // pi only supports 8 bit words
  maxSpeedHz: 8000000 //Hz
};
const nkk_switch = spi.open(0, 0, options, err => {
  // An SPI message is an array of one or more read+write transfers

  const message = [{
    sendBuffer: Buffer.from([ 0x40, 0x03, 0x41, 0x1F]), // Sent to initialize
    //receiveBuffer: Buffer.alloc(3),              // Raw data rno answer
    byteLength: 4,
    speedHz: 8000000 // Use a low bus speed to get a good reading from the TMP36
  }];

  if (err) {
    throw err;
  }

  nkk_switch.transfer(message, (err, message) => {
    if (err) {
      throw err;
    }

   
    console.log('sent initialize');

  });

  const message1 = [{
    sendBuffer: Buffer.from([0x40, 0x33, 0x41, 0xBF]), // Sent backlight RED FULL
    //receiveBuffer: Buffer.alloc(3),              // Raw data read 
    byteLength: 4,
    speedHz: 8000000 
  }];
  nkk_switch.transfer(message1, (err, message) => {
    if (err) {
      throw err;
    } 
    console.log('sent message1');
  });
});

Now the goal is to use the two library GPIO and SPI to manage the button.
GPIO to detect Raising & falling edge, how long it was pressed and next but hope to close today is to generate bitmap array and send lsb first ;-)


Best Regards,
Youssef

**Comment by fivdi** [comment]
This
```js
const spi = require('spi-device');
```
is better than this:
```js
const spi = require('bindings')('spi');
```
Also, I'd highly recommend sending the second message in the completion callback of first message.

**Comment by yboujraf** [comment]
Dear @fivdi 

Yes I was to say you if I clone the repository, I have an issue with this line 
```
const spi = require('bindings')('spi');
```
doesn't work.

Usually I am not working with npm install the package to be sure I have all the repository with uglify, ....

```
Also, I'd highly recommend sending the second message in the completion callback of first message.
```

IF you could give me an example I am not expert ;-)

Best Regards,
Youssef

**Comment by yboujraf** [comment]
Dear @fivdi 

Back again,

I am trying to generate a bitmap just by forcing a value just to be sure I could see anything.

My question,

I am creating the message :
```
  let bitmapbuffer = new ArrayBuffer(257); // create a buffer of length 16
  bitmapbuffer[0] = 0x55;
  var i = 1;
  for (i = 1; i < 257; i++) {
    bitmapbuffer[i] = 0x03;
  }
  console.log(`nbr bytes ${bitmapbuffer.byteLength} ...`)
  console.log(bitmapbuffer)

  const messageBitmap = [{
    sendBuffer: Buffer.from(bitmapbuffer), // Sent backlight GREEN FULL
    byteLength: 257,
    speedHz: 8000000
  }];
```
I can check log that the bytearray is correctly created but no way to see if it sent or if :+1: 

```
sendBuffer: Buffer.from(bitmapbuffer), // Sent backlight GREEN FULL
```

From the button, no feedback. If the bytearray is malformed or missing anything automatically the button reject the new command.

Thanks if you could confirm the way I am creating the 257 bytes are correctly implemented in the sendbuffer.


Best regards
Youssef

**Comment by fivdi** [comment]
>>Also, I'd highly recommend sending the second message in the completion callback of first message.
>
>IF you could give me an example I am not expert ;-)

Something like this:
```js
'use strict';

const spi = require('bindings')('spi');

// Determine the temperature using a TMP36 analog temperature sensor wired to
// channel 5 on an MCP3008 SPI A/D converter

const options = {
  mode: spi.MODE2,
  chipSelectHigh: false,
  lsbFirst: false, // pi only supports msb first
  threeWire: false,
  loopback: false, // pi doesn't support loopback
  noChipSelect: false,
  ready: false, // pi doesn't support ready
  bitsPerWord: 8, // pi only supports 8 bit words
  maxSpeedHz: 8000000 //Hz
};
const nkk_switch = spi.open(0, 0, options, err => {
  // An SPI message is an array of one or more read+write transfers

  const message = [{
    sendBuffer: Buffer.from([ 0x40, 0x03, 0x41, 0x1F]), // Sent to initialize
    //receiveBuffer: Buffer.alloc(3),              // Raw data rno answer
    byteLength: 4,
    speedHz: 8000000 // Use a low bus speed to get a good reading from the TMP36
  }];

  if (err) {
    throw err;
  }

  nkk_switch.transfer(message, (err, message) => {
    if (err) {
      throw err;
    }

    console.log('sent initialize');

    const message1 = [{
      sendBuffer: Buffer.from([0x40, 0x33, 0x41, 0xBF]), // Sent backlight RED FULL
      //receiveBuffer: Buffer.alloc(3),              // Raw data read 
      byteLength: 4,
      speedHz: 8000000 
    }];

    nkk_switch.transfer(message1, (err, message) => {
      if (err) {
        throw err;
      } 

      console.log('sent message1');
    });
  });
});
```

**Comment by fivdi** [comment]
The following code doesn't do what you think it does.
```js
  let bitmapbuffer = new ArrayBuffer(257); // create a buffer of length 16
  bitmapbuffer[0] = 0x55;
  var i = 1;
  for (i = 1; i < 257; i++) {
    bitmapbuffer[i] = 0x03;
  }
  console.log(`nbr bytes ${bitmapbuffer.byteLength} ...`)
  console.log(bitmapbuffer)

  const messageBitmap = [{
    sendBuffer: Buffer.from(bitmapbuffer), // Sent backlight GREEN FULL
    byteLength: 257,
    speedHz: 8000000
  }];
```
Try this instead:
```js
  let bitmapbuffer = Buffer.alloc(257);
  bitmapbuffer[0] = 0x55;
  var i = 1;
  for (i = 1; i < 257; i++) {
    bitmapbuffer[i] = 0x03;
  }
  console.log(`nbr bytes ${bitmapbuffer.length} ...`)
  console.log(bitmapbuffer)

  const messageBitmap = [{
    sendBuffer: bitmapbuffer, // Sent backlight GREEN FULL
    byteLength: 257,
    speedHz: 8000000
  }];
```

**Comment by yboujraf** [comment]
Dear @fivdi 

Thanks for your reply.

Finally, i did it.

![2019-12-30-150353_3840x2160_scrot](https://user-images.githubusercontent.com/6151258/71585095-b8071180-2b15-11ea-97a6-fd6d71c6bf8f.png)

### How to close or disconnect SPI ?

Just to be sure, when the message are sent at the end you close the SPI connection or there is a disconnect or close command to sent?

And there is a way to wake up the SPI if any message is coming to the raspberry ?


### For the next 

- Now I need to clean the code and generate enum for command, color set, background set, managing bitmap array.

- Missing a bitmap array to generate text in 1 till ' lines with autosize or wrapping, .... and for eacfh line to be able to invert the background color ;

Long mission.



Otherwise, the source code is C as far as I know, but did you have any time got memory leaks or updated with the latest commit from the original source ?

Otherwise if you have other protocol like modbus, it will be nice to have as controller or device ;-)


### Finally is to create a board to support 16/33/50 bitmap push button with one rotary button magnetic in spi too or I2C and I think I need to replace the CE0 by usingthe  MCP23017 https://www.microchip.com/wwwproducts/en/MCP23017

too much protocol in use and I need another mcp2317 for the push button too.

How do you think boss ;-)

I am sure you have better idea .

Best Regards
Youssef

**Comment by fivdi** [comment]
>Finally, i did it.

Congratulations :smile:

>How to close or disconnect SPI ?
>
>Just to be sure, when the message are sent at the end you close the SPI connection or there is a disconnect or close command to sent?

It's not really necessary to invoke `close` on `SpiDevice` objects in most scenarios. An `SpiDevice` object can be opened (created) for each SPI device when the program starts and left open for the lifetime of the program. Under the covers, invoking `open` opens a file for communication with the device. Invoking `close` will close that file and free the corresponding resources.

If a program continuously created many `SpiDevice` objects for whatever reason, it would need to invoke `close` at some point as each process can only have a limited number of open files.

>And there is a way to wake up the SPI if any message is coming to the raspberry ?

Something like this shouldn't be needed. Just open the required `SpiDevice` objects and leave them open. Then they can be used whenever needed.

>Otherwise, the source code is C as far as I know, but did you have any time got memory leaks or updated with the latest commit from the original source ?

I'm not sure which source code you are referring to here. Do you mean the source code from this repository? If so, it's implemented in C++ and I'm not aware of any memory leaks. I don't know which original source you are referring to.

>Finally is to create a board to support 16/33/50 bitmap push button with one rotary button magnetic in spi too or I2C and I think I need to replace the CE0 by usingthe MCP23017

50 bitmap buttons means 50 chip select output lines and 50 button input lines which is 100 lines and additional lines will be needed for MISO/MOSI/SCLK (SPI) and SDA/SCL (I2C). That's more that a Raspberry Pi has and means it can only work with I/O expanders.

4 I/O expanders will be needed for the 50 buttons and each I/O expander will have 2 interrupt outputs which means 8 interrupt inputs for the Raspberry Pi.

A Raspberry Pi 4 has up to 5 SPI ports and up to 6 I2C ports (see [here](https://www.raspberrypi.org/documentation/hardware/raspberrypi/bcm2711/rpi_DATA_2711_1p0_preliminary.pdf)). Perhaps it would make sense to use multiple SPI and I2C ports at the same time.

It will be interesting to see how the project goes particularly from a performance perspective.

**Comment by yboujraf** [comment]
Dear @fivdi 

Regarding C library ; https://github.com/fivdi/spi-device/tree/master/src

In the src folder I can find all the code in C.

Did you made a wrapper to JS ?

I am interrested because the manufacturer of the button sent me yesterday the c library in for raspberry and would make a js wrapper on it otherwise I will rewrite the code.

Best Regards
BEst Wishes for 2020 cheers 

Youssef

**Comment by fivdi** [comment]
>Regarding C library ; https://github.com/fivdi/spi-device/tree/master/src
>
>In the src folder I can find all the code in C.

As mentioned above, the code in https://github.com/fivdi/spi-device/tree/master/src is C++ code.

> Did you made a wrapper to JS ?

spi-device was implemented in a way that makes it directly callable from JavaScript without the need for a wrapper.

[i2c-bus](https://github.com/fivdi/i2c-bus) was implemented in a way that requires a wrapper.

**Comment by yboujraf** [comment]
Dear @fivdi 

Sorry to ask too much question, I am beginner with javascript.

Do you have a tuto how to make the wrapper from C to javascript or typescript ?

I have a lot of library in C or C++ but my team doesn't want to use C or c++ only typescript  in first and javascript in second ;-)

The manufacturer sent me the library in C for raspberry PI3 

[NKK Raspberry Pi Source Code.zip](https://github.com/fivdi/spi-device/files/4012596/NKK.Raspberry.Pi.Source.Code.zip)

And now need to convert it in typescript or java.

Apology but I respect you and never in github I have seen somebody like you sharing with happiness your knowledge.

Again many thanks.
Youssef

**Comment by fivdi** [comment]
> Do you have a tuto how to make the wrapper from C to javascript or typescript ?

I'm afraid I don't.

A lot of the knowledge that I have is from the [nan examples](https://github.com/nodejs/nan/tree/master/examples) and [nan tests](https://github.com/nodejs/nan/tree/master/test).

Note that using nan for Node.js addons is an old technique. A more modern approach would be to use  N-API. See [here](https://nodejs.org/api/addons.html) and [here](https://nodejs.org/api/n-api.html).

**Comment by yboujraf** [comment]
Dear @fivdi 

Thanks, I got it but I will spend 10 years to wrap my code ;-)

Best Regards
Cheers
Youssef
