### ISSUE TITLE
Issue with Max31865

### ISSUE THREAD

**Issue by VaderMester** [fivdi/spi-device#14]
I'm using this lib which uses your lib with current version: https://github.com/MariusRumpf/max31865
Platform: Rpi 3B
The library seems to be working software wise, but somehow strange thing happen on the MISO line. It seems that on every clock edge, there is a very short - 100ns- spike on the MISO line. The timing of events seem OK though, as the read and write functions are called.

Did you observ such behaviour before with any SPI device?
I'm using the Adafruit breakout board with the max31865. Just to check if the baord is faulty, I did it with 2 boards, but the same issue is produced.

Here is a screenshot below. As you can see on Chanel 3, which is the MISO, there are spikes on the line. Also as you can see (did not fit the pic) MISO is kept low for longer time, and CS as well. Is it possible for the SPI driver to recognize this as an error?
Strangely, the Pi is not recognizing data. Printing values are all 0, which means to me that no real value is recognized.
I doubt that it is the lib issue, it should be a SPI related one, but I'm not sure how to start debugging this.
The screenshot actually shows the rtd reading sequence from the Max31865 (address 0x01), as you can see there is -kinda - a valid value.
Clock is measured 312,5kHz. The Max31685 supports both Mode1 and Mode3, tested with both, same result. Screenshot shows Mode1.
![image](https://user-images.githubusercontent.com/25725282/78576662-47b30f00-782d-11ea-8275-f2b4178249e2.png)

**Comment by VaderMester** [comment]
Tried various (510ohm, 1.5k, 10k) resistors from the MOSI to GND and to 3.3V. Issue still persists.

**Comment by fivdi** [comment]
I'm afraid I probably can't provide much useful feedback here.

> Did you observ such behaviour before with any SPI device?

This isn't something I've observed.

> Here is a screenshot below. As you can see on Chanel 3, which is the MISO, there are spikes on the line.

MISO is an input signal on the Rapsberry Pi and if everything is connected up correctly the signal on the MISO line should be coming from the breakout board. I can't imagine that either the Raspberry Pi SPI driver or the spi-device module are responsible for generating these spikes.

> Also as you can see (did not fit the pic) MISO is kept low for longer time, and CS as well. Is it possible for the SPI driver to recognize this as an error?

I don't know. Why should the driver recognize this as an error? The CS signal is generated by the SPI driver.

> Tried various (510ohm, 1.5k, 10k) resistors from the MOSI to GND and to 3.3V. Issue still persists.

Pull-up or pull-down resistors shouldn't be necessary.

**Comment by VaderMester** [comment]
So, I did some more testing.
The Max31865 tristates the output pin properly.
It seems that the Raspberry actively drives the MISO pin high!
RPi powered off, the MISO line is GND, then sometime during the boot, then while monitoring the pin, it becomes 3,3V, without the slave connected, which tells me, that the Pi is driving it.
It stays 3.3V even when I put a 10k pull-down resistor, so it should be a pretty stond drive. No wonder why the Max31865 struggles to work it.
This should not happen, should it?

After this, I disabled the SPI interface, rebooted, and the high-drive on the MISO pin disappeared.
Then reenabled it and again it is driven high.

**Comment by VaderMester** [comment]
Ok, so the noise issue is gone. One of the NodeJS plugins was driving the MOSI pin as GPIO.
Now the waveform is perfect.
Until this point I was reading 0-s, now I'm reading all 1s in software.
The reading is a problem. Software works correctly, as the faulty read data is processed and sent back to the chip. The MAX31865 chip does it's job.

Wiring is checked thoroughly, and everything is connected correctly to the Pi. Using the 3,3V rail of the pi, and the GND from the Pi as well, everything directly connected to the GPIO Header with jumper cables.
Still wondering why am I reading incorrect data.
![image](https://user-images.githubusercontent.com/25725282/78649603-f43cd180-78bd-11ea-84d0-94931b2dc6de.png)

**Comment by fivdi** [comment]
If you are certain that the hardware has not been damaged by multiple modules driving GPIOs concurrently, I would suggest implementing a small program that uses the spi-device module directly to read the 16 bit RTD register. It should read as 0x0000. Then implement a small program that uses the spi-device module directly to read the 16 bit High Fault Threshold register. It should read as 0xffff.

This will help to figure out if [max31865](https://github.com/MariusRumpf/max31865) is functioning correctly.

If either of the two small programs mentioned above does not function correctly, then either the hardware is damaged or spi-device (or the SPI drivers on the Raspberry Pi) is broken. I currently don't have any reason to believe that spi-device (or the SPI drivers on the Raspberry Pi) is broken.

**Comment by VaderMester** [comment]
OK, so finally fixed it.
I previously used the node-rpio library (https://github.com/jperkin/node-rpio), which seems to be not working with this spi-lib.
I changed to t the node-rpi-gpio lib (https://github.com/JamesBarwell/rpi-gpio.js), which seems to have fixed the issue.
Now I am reading nice temp values :)

It seems to be a compatibility issue that these libraries use /dev/gpiomem or /sys/class/gpio.

I was using this from Homebridge (https://github.com/homebridge/homebridge), without root.
You can close this!

**Comment by fivdi** [comment]
Good to hear that it's working now,

For access to GPIOs consider using onoff (https://github.com/fivdi/onoff) which like spi-device doesn't require root privileges.
