### ISSUE TITLE
Configure options not working

### ISSUE THREAD

**Issue by ajacobs-github** [fivdi/spi-device#17]
Options do not change when setting mode, or any other options.

Code to set and check spi options:
	  let spi_options = [{
		  mode: 0b10,
		  chipSelectHigh: true,
		  lsbFirst: true,
		  threeWire: true,
		  loopback: true,
		  noChipSelect: true,
		  ready: true,
		  bitsPerWord: 8,
		  maxSpeedHz: 125000000 
		  }];

	  console.log('Set SPI Options', spi_options)
	  
	  const pn532 = await spi.openSync(0,0);		// bus 0, device 0
	  await pn532.setOptionsSync(spi_options)

	  console.log('Check SPI Options', await pn532.getOptionsSync())

Output:
[13/11/2020 20:34:22.057] [LOG]    Set SPI Options [ { mode: 2,
    chipSelectHigh: true,
    lsbFirst: true,
    threeWire: true,
    loopback: true,
    noChipSelect: true,
    ready: true,
    bitsPerWord: 8,
    maxSpeedHz: 125000000 } ]
[13/11/2020 20:34:22.092] [LOG]    Check SPI Options { mode: 0,
  chipSelectHigh: false,
  lsbFirst: false,
  threeWire: false,
  loopback: false,
  noChipSelect: false,
  ready: false,
  bitsPerWord: 8,
  maxSpeedHz: 125000000 }

**Comment by fivdi** [comment]
spi_options should be an object, not an array of object.

**Comment by ajacobs-github** [comment]
Thanks for responding so quickly.  I get the Error: EINVAL, Invalid argument, when spi_options is an object:

	  let spi_options = {
		  mode: 2,
		  chipSelectHigh: true,
		  lsbFirst: true,
		  threeWire: true,
		  loopback: true,
		  noChipSelect: true,
		  ready: true,
		  bitsPerWord: 8,
		  maxSpeedHz: 125000000 
		  };

**Comment by fivdi** [comment]
Note that spi_device does not support promises so try with callbacks to see if it works. If it's still not working please post a complete JavaScript program that can be used to reproduce the problem. Also, provide details like type of board, Node version, operating system and version.

**Comment by fivdi** [comment]
Also, not every driver on every operating system supports every option. This may be the source of the EINVAL error.

**Comment by fivdi** [comment]
If you are using a Raspberry Pi, does this test run successfully: 

https://github.com/fivdi/spi-device/blob/master/test/options.js

**Comment by ajacobs-github** [comment]
I am using Raspberry Pi Zero.  Cannot test options.js because spi is not installing.

npm install spi gives the following errors

pi@devraspberrypi:~/orabase $ npm install spi

> spi@0.2.0 install /home/pi/orabase/node_modules/spi
> node-gyp rebuild

make: Entering directory '/home/pi/orabase/node_modules/spi/build'
  CXX(target) Release/obj.target/_spi/src/spi_binding.o
In file included from ../src/spi_binding.h:20,
                 from ../src/spi_binding.cc:19:
/home/pi/.node-gyp/11.15.0/include/node/node.h:544:43: warning: cast between incompatible function types from ‘void (*)(v8::Handle<v8::Object>)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
       (node::addon_register_func) (regfunc),                          \
                                           ^
/home/pi/.node-gyp/11.15.0/include/node/node.h:578:3: note: in expansion of macro ‘NODE_MODULE_X’
   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
   ^~~~~~~~~~~~~
../src/spi_binding.cc:42:3: note: in expansion of macro ‘NODE_MODULE’
   NODE_MODULE(_spi, init)
   ^~~~~~~~~~~
../src/spi_binding.cc: In static member function ‘static void Spi::New(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/spi_binding.cc:105:49: error: no matching function for call to ‘v8::Function::NewInstance()’
     args.GetReturnValue().Set(cons->NewInstance());
                                                 ^
In file included from ../src/spi_binding.h:19,
                 from ../src/spi_binding.cc:19:
/home/pi/.node-gyp/11.15.0/include/node/v8.h:4105:44: note: candidate: ‘v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>, int, v8::Local<v8::Value>*) const’
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                            ^~~~~~~~~~~
/home/pi/.node-gyp/11.15.0/include/node/v8.h:4105:44: note:   candidate expects 3 arguments, 0 provided
/home/pi/.node-gyp/11.15.0/include/node/v8.h:4108:44: note: candidate: ‘v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const’
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                            ^~~~~~~~~~~
/home/pi/.node-gyp/11.15.0/include/node/v8.h:4108:44: note:   candidate expects 1 argument, 0 provided
../src/spi_binding.cc: In static member function ‘static void Spi::Open(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/spi_binding.cc:115:46: warning: ‘v8::Local<v8::String> v8::Value::ToString() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   String::Utf8Value device(args[0]->ToString());
                                              ^
In file included from ../src/spi_binding.h:19,
                 from ../src/spi_binding.cc:19:
/home/pi/.node-gyp/11.15.0/include/node/v8.h:10251:15: note: declared here
 Local<String> Value::ToString() const {
               ^~~~~
../src/spi_binding.cc:115:47: warning: ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’ is deprecated: Use Isolate version [-Wdeprecated-declarations]
   String::Utf8Value device(args[0]->ToString());
                                               ^
In file included from /home/pi/.node-gyp/11.15.0/include/node/v8.h:26,
                 from ../src/spi_binding.h:19,
                 from ../src/spi_binding.cc:19:
/home/pi/.node-gyp/11.15.0/include/node/v8.h:2992:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^~~~~~~~~
/home/pi/.node-gyp/11.15.0/include/node/v8config.h:326:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/spi_binding.cc: In static member function ‘static void Spi::Transfer(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/spi_binding.cc:160:42: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     write_buffer_obj = args[0]->ToObject();
                                          ^
In file included from ../src/spi_binding.h:19,
                 from ../src/spi_binding.cc:19:
/home/pi/.node-gyp/11.15.0/include/node/v8.h:10257:15: note: declared here
 Local<Object> Value::ToObject() const {
               ^~~~~
../src/spi_binding.cc:166:41: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     read_buffer_obj = args[1]->ToObject();
                                         ^
In file included from ../src/spi_binding.h:19,
                 from ../src/spi_binding.cc:19:
/home/pi/.node-gyp/11.15.0/include/node/v8.h:10257:15: note: declared here
 Local<Object> Value::ToObject() const {
               ^~~~~
../src/spi_binding.cc: In member function ‘void Spi::full_duplex_transfer(v8::Isolate*, const v8::FunctionCallbackInfo<v8::Value>&, char*, char*, size_t, uint32_t, uint16_t, uint8_t)’:
../src/spi_binding.cc:199:3: warning: missing initializer for member ‘spi_ioc_transfer::cs_change’ [-Wmissing-field-initializers]
   };
   ^
../src/spi_binding.cc:199:3: warning: missing initializer for member ‘spi_ioc_transfer::tx_nbits’ [-Wmissing-field-initializers]
../src/spi_binding.cc:199:3: warning: missing initializer for member ‘spi_ioc_transfer::rx_nbits’ [-Wmissing-field-initializers]
../src/spi_binding.cc:199:3: warning: missing initializer for member ‘spi_ioc_transfer::pad’ [-Wmissing-field-initializers]
../src/spi_binding.cc: In member function ‘bool Spi::get_argument(v8::Isolate*, const v8::FunctionCallbackInfo<v8::Value>&, int, int&)’:
../src/spi_binding.cc:356:36: warning: ‘int32_t v8::Value::Int32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   value = args[offset]->Int32Value();
                                    ^
In file included from /home/pi/.node-gyp/11.15.0/include/node/v8.h:26,
                 from ../src/spi_binding.h:19,
                 from ../src/spi_binding.cc:19:
/home/pi/.node-gyp/11.15.0/include/node/v8.h:2572:46: note: declared here
   V8_DEPRECATED("Use maybe version", int32_t Int32Value() const);
                                              ^~~~~~~~~~
/home/pi/.node-gyp/11.15.0/include/node/v8config.h:326:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/spi_binding.cc: In member function ‘bool Spi::get_argument(v8::Isolate*, const v8::FunctionCallbackInfo<v8::Value>&, int, bool&)’:
../src/spi_binding.cc:372:38: warning: ‘bool v8::Value::BooleanValue() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   value = args[offset]->BooleanValue();
                                      ^
In file included from /home/pi/.node-gyp/11.15.0/include/node/v8.h:26,
                 from ../src/spi_binding.h:19,
                 from ../src/spi_binding.cc:19:
/home/pi/.node-gyp/11.15.0/include/node/v8.h:2568:43: note: declared here
   V8_DEPRECATED("Use maybe version", bool BooleanValue() const);
                                           ^~~~~~~~~~~~
/home/pi/.node-gyp/11.15.0/include/node/v8config.h:326:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/spi_binding.h:19,
                 from ../src/spi_binding.cc:19:
/home/pi/.node-gyp/11.15.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]’:
/home/pi/.node-gyp/11.15.0/include/node/node_object_wrap.h:84:78:   required from here
/home/pi/.node-gyp/11.15.0/include/node/v8.h:9710:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<node::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
                reinterpret_cast<Callback>(callback), type);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [_spi.target.mk:97: Release/obj.target/_spi/src/spi_binding.o] Error 1
make: Leaving directory '/home/pi/orabase/node_modules/spi/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:193:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:255:12)
gyp ERR! System Linux 4.19.75+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/orabase/node_modules/spi
gyp ERR! node -v v11.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/orabase/package.json'
npm WARN @unimodules/react-native-adapter@5.6.0 requires a peer of react-native@* but none is installed. You must install peer dependencies yourself.
npm WARN @unimodules/react-native-adapter@5.6.0 requires a peer of react-native-web@~0.13.7 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-securerandom@0.1.1 requires a peer of react-native@* but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.2.1 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.2.1 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN orabase No description
npm WARN orabase No repository field.
npm WARN orabase No README data
npm WARN orabase No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! spi@0.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the spi@0.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-11-14T18_03_04_652Z-debug.log

**Comment by fivdi** [comment]
The command `npm install spi` doesn't Install spi-device.

**Comment by ajacobs-github** [comment]
Your test code has
const spi = require('bindings')('spi');

did you mean 
const spi = require('bindings')('spi-device');
?

**Comment by fivdi** [comment]
To run the test code it's not necessary to install any additional modules. Just run the test script directly from the command line:
```console
$ cd node_modules/spi-device/test/
$ node options
```

**Comment by ajacobs-github** [comment]
Got it.  It does not work when setting lsbFirst to true. I added console.log to show the SPI options being set and readback.

pi@devraspberrypi:~/orabase/node_modules/spi-device/test $ node options.js
SPI Set Options to: { mode: 3,
  chipSelectHigh: true,
  lsbFirst: true,
  threeWire: true,
  loopback: false,
  noChipSelect: true,
  ready: false,
  bitsPerWord: 8,
  maxSpeedHz: 125010000 }
assert.js:341
    throw err;
    ^

AssertionError [ERR_ASSERTION]: can't set options
    at device.setOptions.err (/home/pi/orabase/node_modules/spi-device/test/options.js:27:7)
pi@devraspberrypi:~/orabase/node_modules/spi-device/test $

**Comment by ajacobs-github** [comment]
Also does not work for loopback: true, or ready: true, or bitsPerWord: 7.

**Comment by fivdi** [comment]
Yes, this is correct. As mentioned [here](https://github.com/fivdi/spi-device/issues/17#issuecomment-727153594), not every driver on every operating system supports every option. If I remember correctly, the Raspberry Pi supports mode, chipSelectHigh, threeWire, noChipSelect, bitsPerWord:8 and maxSpeedHz. This is not an issue with the spi-device Node Module.

**Comment by ajacobs-github** [comment]
Thanks.  The Raspberry Pi SPI driver does not support lsbfirst.  I did the bit reverse in code before sending the packet and got it to work, but I had to manually toggle a different GPIO for chip select.

Does spi-device support chip select CE0 or CE1 on the RPi?  I have scoped both of these pins, and both stay low when SCK and MOSI are sending data.

**Comment by fivdi** [comment]
>  The Raspberry Pi SPI driver does not support lsbfirst. I did the bit reverse in code before sending the packet and got it to work

That's good news.

> but I had to manually toggle a different GPIO for chip select.
>
> Does spi-device support chip select CE0 or CE1 on the RPi?

Yes, it does. I have just verified this to be the case while running [this](https://github.com/fivdi/spi-device/blob/master/test/stress/brute-force-leak-check.js) test program and I can see that CE0 changes state while the program is running.

Has SPI been configured correctly in /boot/config.txt?
Can you post the complete contents of /boot/config.txt?
What type of SPI devices are being connected to the Raspberry Pi?
Are the correct pins being used for CE0 and CE1?

**Comment by fivdi** [comment]
@ajacobs-github Have you any news related to this issue?

**Comment by fivdi** [comment]
I'm going to go ahead and assume all is ok with spi-device here and close the issue. If it does turn out to be an issue with spi-device the ticket can be reopened.
