### ISSUE TITLE
Bump nan

### ISSUE THREAD

**Issue by robertalexa** [fivdi/spi-device#23]
Hi,

Would it be possible you bump nan to latest version 2.15.0?

Many thanks

**Comment by fivdi** [comment]
The latest version of spi-device, currently spi-device@3.1.2, defines its dependency on nan like [this](https://github.com/fivdi/spi-device/blob/v3.1.2/package.json#L25):

```
    "nan": "^2.14.2"
```

As can be seen below, this means that if the latest version of spi-device is installed, nan@2.15.0 will also be installed:

```
$ npm i spi-device

added 4 packages, and audited 5 packages in 51s

found 0 vulnerabilities
brian@linuxbox:~/test$ npm list --all
test@ /home/brian/test
└─┬ spi-device@3.1.2
  ├─┬ bindings@1.5.0
  │ └── file-uri-to-path@1.0.0
  └── nan@2.15.0

$ 
```

Is this not the case on your system?
Can you please explain the issue you would like to resolve by updating the nan dependency in spi-device to nan@2.15.0?

**Comment by fivdi** [comment]
I'll go ahead and close this issue as there doesn't appear to be a problem with spi-device. If it turns out that there is a problem, the issue can be reopened.
