### ISSUE TITLE
correct values for speedHz and maxSpeedHz settings on Raspberry Pi?

### ISSUE THREAD

**Issue by fquirin** [fivdi/spi-device#25]
The [Raspberry Pi documentation](https://www.raspberrypi.com/documentation/computers/raspberry-pi.html#spi-overview) says this about SPI speeds:

>The driver supports all speeds which are even integer divisors of the core clock, although as said above not all of these speeds will support data transfer due to limits in the GPIOs and in the devices attached. As a rule of thumb, anything over 50MHz is unlikely to work, but your mileage may vary.

The core clock is usually given as 500Mhz for Raspberry Pi 4 and I've added `core_freq_min=500` to my /boot/config.txt as mentioned in many tutorials to prevent drift.
This gives us the following values for speed:
```
31.25 Mhz
15.625 Mhz
7.8125 Mhz
3.90625 Mhz
1.953125 Mhz
...
```

I was wondering if this actually applies or if there is something else going on that can set speeds in between?

I've been trying to control a ws281x RGB LED via SPI and I'm getting very confusing results. The correct speed should be 2.35 Mhz in my case but the only reasonable results happen at 9-10 Mhz :confused: which actually should not even exist ...

Any help or ideas would be awesome!

**Comment by fquirin** [comment]
So I spent several hours with this the last days, then I post my question here ... and 1h later I think I found the solution :laughing: 

Turns out the 'maxSpeedHz' actually does what it says (who would have thought :-p) and sets the MAX CORE SPEED. The 'speedHz' can then become a value given by CORE/(n*2). 
So I set 'maxSpeedHz' to 4.7Mhz and 'speedHz' to 2.35Mhz and finally got it working predictable and reliable :star_struck: . Just setting max and speed both to 2.35 MHz didn't seem to work though :thinking:

**Comment by fivdi** [comment]
Good to hear that it's now working 😄
