### ISSUE TITLE
GPIO pins as chip select

### ISSUE THREAD

**Issue by eczajk1** [fivdi/spi-device#4]
Is it possible to use this library to control a [DAC8532](https://www.waveshare.com/wiki/File:DAC8532-datasheet.pdf) via this ["High Precision AD/DA Board"](https://www.waveshare.com/wiki/High-Precision_AD/DA_Board)?

I'm getting confused because the board seems to use GPIO pins 23 and 22 as CS for the onboard digital-to-analog and analog-to-digital converters, respectively.

The board [schematic](https://www.waveshare.com/wiki/File:High-Precision-AD-DA-board.pdf) doesn't seem to indicate any connection for the SPI CSx pins (GPIO 7 and 8).

I was thinking that this might be the type of scenario where `noChipSelect` would get used (i.e. use `onoff` to control chip select directly via the GPIO pins) - but nothing I try seems to work.

Any guidance appreciated. Thanks for this library.

**Comment by fivdi** [comment]
> Is it possible to use this library to control a DAC8532 via this "High Precision AD/DA Board"?

I don't know as I've never tried it but if I had to guess I'd say it should work.

> I'm getting confused because the board seems to use GPIO pins 23 and 22 as CS for the onboard digital-to-analog and analog-to-digital converters, respectively.

Yes, this is confusing. But your analysis looks right to me.
GPIO23 is the chip select for the DAC8552 (the schematic says it's a DAC8552 not a DAC8532.)
GPIO22 is the chip select for the ADS1256.

> The board schematic doesn't seem to indicate any connection for the SPI CSx pins (GPIO 7 and 8).

Yes, this is also confusing but appears to be the way it is.

> I was thinking that this might be the type of scenario where noChipSelect would get used (i.e. use onoff to control chip select directly via the GPIO pins)

This sounds like it should work to me too.

> but nothing I try seems to work.

Have you compared your code with the code in dac8532_test.c which can be downloaded [here](https://www.waveshare.com/wiki/File:High-Precision-AD-DA-Board-Code.7z) to see if everything is being done correctly?

**Comment by eczajk1** [comment]
I had read through that code. But now that I did again, I realize I was writing to the shift registers incorrectly.

Thanks for your help!

**Comment by fivdi** [comment]
That sounds good. Hopefully it's working now.

The code in  dac8532_test.c does three transfers for each write:
```c
      bcm2835_spi_transfer(channel);
      bcm2835_spi_transfer((Data>>8));
      bcm2835_spi_transfer((Data&0xff)); 
```
With spi-device only one transfer should be needed as all three bytes can be put in sendBuffer.

**Comment by eczajk1** [comment]
Thanks again for your help on this. Posting these in case it can help anyone:
- [ADS125x](https://github.com/CenturyGIS/ADS125x)
- [DAC8552](https://github.com/CenturyGIS/DAC8552)

**Comment by fivdi** [comment]
@eczajk1 Nice :smile:
Thanks for the feedback and links.
