### ISSUE TITLE
Can you please help me with this issue not able to install spi-device module 

### ISSUE THREAD

**Issue by LochanRn** [fivdi/spi-device#5]
pi@raspberrypi:~/SPI $ npm install spi-device

> spi-device@1.0.2 install /home/pi/SPI/node_modules/spi-device
> node-gyp rebuild

make: Entering directory '/home/pi/SPI/node_modules/spi-device/build'
make: Warning: File '../../../../.node-gyp/8.9.4/include/node/common.gypi' has modification time 3888180 s in the future
  ACTION Regenerating Makefile
make: Warning: File '../../../../.node-gyp/8.9.4/include/node/common.gypi' has modification time 3888179 s in the future
  ACTION Regenerating Makefile
make: Warning: File '../../../../.node-gyp/8.9.4/include/node/common.gypi' has modification time 3888178 s in the future
  ACTION Regenerating Makefile
make: Warning: File '../../../../.node-gyp/8.9.4/include/node/common.gypi' has modification time 3888177 s in the future
  ACTION Regenerating Makefile
make: Warning: File '../../../../.node-gyp/8.9.4/include/node/common.gypi' has modification time 3888176 s in the future
  ACTION Regenerating Makefile
make: Warning: File '../../../../.node-gyp/8.9.4/include/node/common.gypi' has modification time 3888174 s in the future
  ACTION Regenerating Makefile
make: Warning: File '../../../../.node-gyp/8.9.4/include/node/common.gypi' has modification time 3888173 s in the future
  ACTION Regenerating Makefile
make: Warning: File '../../../../.node-gyp/8.9.4/include/node/common.gypi' has modification time 3888172 s in the future
  ACTION Regenerating Makefile
make: Warning: File '../../../../.node-gyp/8.9.4/include/node/common.gypi' has modification time 3888171 s in the future
  ACTION Regenerating Makefile
make: Warning: File '../../../../.node-gyp/8.9.4/include/node/common.gypi' has modification time 3888170 s in the future
  ACTION Regenerating Makefile
make: Warning: File '../../../../.node-gyp/8.9.4/include/node/common.gypi' has modification time 3888168 s in the future
  ACTION Regenerating Makefile
make: Warning: File '../../../../.node-gyp/8.9.4/include/node/common.gypi' has modification time 3888167 s in the future
  ACTION Regenerating Makefile
^CProcess PoolWorker-3:
Process PoolWorker-4:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process PoolWorker-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 102, in worker
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 102, in worker
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 102, in worker
    task = get()

**Comment by LochanRn** [comment]
pi@raspberrypi:~/SPI/node_modules/spi-device $ node spi-device.js
/home/pi/SPI/node_modules/bindings/bindings.js:96
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /home/pi/SPI/node_modules/spi-device/build/spi.node
 → /home/pi/SPI/node_modules/spi-device/build/Debug/spi.node
 → /home/pi/SPI/node_modules/spi-device/build/Release/spi.node
 → /home/pi/SPI/node_modules/spi-device/out/Debug/spi.node
 → /home/pi/SPI/node_modules/spi-device/Debug/spi.node
 → /home/pi/SPI/node_modules/spi-device/out/Release/spi.node
 → /home/pi/SPI/node_modules/spi-device/Release/spi.node
 → /home/pi/SPI/node_modules/spi-device/build/default/spi.node
 → /home/pi/SPI/node_modules/spi-device/compiled/8.9.4/linux/arm/spi.node
    at bindings (/home/pi/SPI/node_modules/bindings/bindings.js:93:9)
    at Object.<anonymous> (/home/pi/SPI/node_modules/spi-device/spi-device.js:1:99)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

**Comment by fivdi** [comment]
The time settings on the Raspberry Pi appear to be incorrect. I have seen similar issues in the past when the time settings were incorrect. If Raspbian is the Operating System being used and the Raspberry Pi is connected to the Internet the it should get the time from the Internet automatically. Another typical symptom of incorrect time settings is when the `date` command doesn't print the correct date. This isn't an spi-device issue.

**Comment by fivdi** [comment]
One additional point. `spi-device` is a module that is intended for usage in other modules or applications. Running `node spi-device.js` from the command line isn't the correct way to use `spi-devce`.

**Comment by LochanRn** [comment]
I installed the module and tried using it in other module but it pops up the same message as before so I reinstalled the module to check if it is correct. Thank you for the help will get back to you if I need any :)

**Comment by LochanRn** [comment]
After updating the time settings in raspberry pi 3 is showing nov 29 2017 10:49.

**Comment by fivdi** [comment]
> After updating the time settings in raspberry pi 3 is showing nov 29 2017 10:49.

If the Raspberry Pi 3 is displaying the incorrect date then the time was not updated correctly.

I'd suggest asking how to set the time correctly on your Raspberry Pi at the Raspberry Pi forum which is at https://www.raspberrypi.org/forums/

I'm going to go ahead and close this issue as it's not related to the spi-device module.
