### ISSUE TITLE
Add platform-conditional directive around spidev include

### ISSUE THREAD

**Issue by alexeden** [fivdi/spi-device#7]
Trying to install this package locally on a mac. Getting this error:

```
../src/spi.cc:1:10: fatal error: 'linux/spi/spidev.h' file not found
#include <linux/spi/spidev.h>
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.
```

Makes sense, given that that library wouldn't exist on a mac. I noticed that in the pi-spi package, [there's  an `#if __linux__` conditional around the inclusion of the SPI library.](https://github.com/natevw/pi-spi/blob/master/spi_binding.cc#L13) Would it make sense to include something like that in this package as well? Ideally I'd be able to run `npm install` anywhere without a breakdown.

**Comment by fivdi** [comment]
If `spi-device` is added to `package.json` in the `optionalDependencies` object rather than in the `dependencies` object then then it should be possible to achieve what you would like to achieve. There will be errors installing `spi-device` but npm will not terminate with an error while installing.

**Comment by alexeden** [comment]
Fair enough!
