### ISSUE TITLE
can't find SPI device channel arguments!

### ISSUE THREAD

**Issue by nilipta** [fivdi/spi-device#8]
Hi fivdi, I want to thank you for building a great module for SPI interface. Right now this module is the most decent one in whole embedded world using JavaScript. As limitation due to my knowledge I am not sure how can I get the reading of a channel by parameter  sendBuffer in message object ! Can I get a documentation in somewhere? Any help is appreciated.

**Comment by fivdi** [comment]
Can you post a link to the datasheet for the device that you would like to communicate with using `spi-device`?

**Comment by fivdi** [comment]
If the goal is to read the value of a TMP36 temperature sensor connected to an analog input channel on an MCP3008 using the example code from the readme, then replacing [the following code](https://github.com/fivdi/spi-device/blob/v2.0.6/example/mcp3008-tmp36.js#L11-L16)...
```js
  const message = [{
    sendBuffer: Buffer.from([0x01, 0xd0, 0x00]), // Sent to read channel 5
    receiveBuffer: Buffer.alloc(3),              // Raw data read from channel 5
    byteLength: 3,
    speedHz: 20000 // Use a low bus speed to get a good reading from the TMP36
  }];
```
...with this code...
```js
  const channel = 5;
  const message = [{
    sendBuffer: Buffer.from([0x01, 0x80 + (channel << 4), 0x00]),
    receiveBuffer: Buffer.alloc(3),
    byteLength: 3,
    speedHz: 20000 // Use a low bus speed to get a good reading from the TMP36
  }];
```
...should do it. Just set `channel` to the appropriate channel number,

Alternaticely, [mcp-spi-adc](https://github.com/fivdi/mcp-spi-adc) could be used.

**Comment by nilipta** [comment]
> Can you post a link to the datasheet for the device that you would like to communicate with using `spi-device`?

Thank you. I am attaching the datasheet of ads1118 for SPI interface through this module. 
[http://www.ti.com/lit/ds/symlink/ads1118.pdf](url)

So my question is how to prepare sendBuffer in message object for this!

**Comment by fivdi** [comment]
I'm afraid I'm not familiar with the ADS1118 and it would take me several hours to read the datasheet and figure out how to use the device. I'd suggest searching for sample code that can be used in combination with the datasheet to figure out what needs to be done.
